<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'id'                 => 1,
                'name'         => 'Stephen Owago',
                'email'              => 'stephen@ims.co.ke',
                'phone'              => '254713218312',
                'is_approved'        => 1,
                'role_id'              => 1,
                'password'           => bcrypt('Owagostv@123'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 2,
                'name'         => 'King Kaka',
                'email'              => 'Artist@ims.co.ke',
                'phone'              => '254713218311',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 3,
                'name'         => 'Khaligraph Jones',
                'email'              => 'Artist1@artist.com',
                'phone'              => '254713218313',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 4,
                'name'         => 'Simple Boy',
                'email'              => 'Artist2@ims.co.ke',
                'phone'              => '254713218314',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 5,
                'name'         => 'Avril',
                'email'              => 'Artist3@ims.co.ke',
                'phone'              => '254713218315',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 6,
                'name'         => 'Nikita Kering',
                'email'              => 'Artist4@ims.co.ke',
                'phone'              => '254713218316',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 7,
                'name'         => 'Meja Okwonko',
                'email'              => 'Artist5@ims.co.ke',
                'phone'              => '254713218317',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 8,
                'name'         => 'Otile Brown',
                'email'              => 'Artist6@ims.co.ke',
                'phone'              => '254713218318',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 9,
                'name'         => 'Willy Paul',
                'email'              => 'Artist7@ims.co.ke',
                'phone'              => '254713218319',
                'is_approved'        => 0,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 10,
                'name'         => 'Bahati B',
                'email'              => 'Artist8@ims.co.ke',
                'phone'              => '254703218312',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 11,
                'name'         => 'Nadia Mukami',
                'email'              => 'Artist9@ims.co.ke',
                'phone'              => '254723218312',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 12,
                'name'         => 'Tanasha Donna',
                'email'              => 'Artist10@ims.co.ke',
                'phone'              => '254733218312',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 13,
                'name'         => 'Akothe One',
                'email'              => 'Artist11@ims.co.ke',
                'phone'              => '254743218312',
                'is_approved'        => 0,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 14,
                'name'         => 'Nyashinski',
                'email'              => 'Artist12@ims.co.ke',
                'phone'              => '254753218312',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
            [
                'id'                 => 15,
                'name'         => 'Pascal Tokodi',
                'email'              => 'Artist13@ims.co.ke',
                'phone'              => '254763218312',
                'is_approved'        => 1,
                'role_id'              => 2,
                'password'           => bcrypt('password'),
                'remember_token'     => null,
                'email_verified_at'        => \Carbon\Carbon::now(),
                'created_at'        => \Carbon\Carbon::now(),
            ],
        ];

        User::insert($users);
    }
}
